#!/bin/sh
# K3 首次启动默认配置
# Bootstrap 主题
uci -q set luci.main.mediaurlbase='/luci-static/bootstrap'
uci -q commit luci
# BBR
sysctl -w net.ipv4.tcp_congestion_control=bbr 2>/dev/null
# ZRAM (256MB + lz4)
uci -q set system.@zram[0].comp_algo='lz4' 2>/dev/null
uci -q set system.@zram[0].zramsize='268435456' 2>/dev/null
uci -q commit system 2>/dev/null
exit 0
